/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alteration: typeof import('./src/components/CircleFifths/sections/Alteration.vue')['default']
    Arrow: typeof import('./src/components/CircleFifths/sections/Arrow.vue')['default']
    BlackNote: typeof import('./src/components/PianoKeyboard/classic/BlackNote.vue')['default']
    Board: typeof import('./src/components/PianoKeyboard/classic/Board.vue')['default']
    ChordIntervals: typeof import('./src/components/ChordIntervals/ChordIntervals.vue')['default']
    ChordName: typeof import('./src/components/ChordName/ChordName.vue')['default']
    ChordNameLink: typeof import('./src/components/ChordNameLink/ChordNameLink.vue')['default']
    CircleFifths: typeof import('./src/components/CircleFifths/CircleFifths.vue')['default']
    DegreeLabel: typeof import('./src/components/CircleFifths/sections/DegreeLabel.vue')['default']
    DegreeLabels: typeof import('./src/components/CircleFifths/sections/DegreeLabels.vue')['default']
    Degrees: typeof import('./src/components/CircleFifths/sections/Degrees.vue')['default']
    Diminished: typeof import('./src/components/CircleFifths/sections/Diminished.vue')['default']
    Dominants: typeof import('./src/components/CircleFifths/sections/Dominants.vue')['default']
    DrawerOutlet: typeof import('./src/components/DrawerOutlet.vue')['default']
    InputNote: typeof import('./src/components/InputNote/InputNote.vue')['default']
    Label: typeof import('./src/components/CircleFifths/sections/Label.vue')['default']
    Labels: typeof import('./src/components/PianoKeyboard/classic/Labels.vue')['default']
    Major: typeof import('./src/components/CircleFifths/sections/Major.vue')['default']
    Minor: typeof import('./src/components/CircleFifths/sections/Minor.vue')['default']
    Modes: typeof import('./src/components/CircleFifths/sections/Modes.vue')['default']
    NavButton: typeof import('./src/components/NavButton.vue')['default']
    Notation: typeof import('./src/components/Notation/Notation.vue')['default']
    Note: typeof import('./src/components/PianoKeyboard/flat/Note.vue')['default']
    PianoKeyboard: typeof import('./src/components/PianoKeyboard/PianoKeyboard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsCollapse: typeof import('./src/components/Settings/SettingsCollapse.vue')['default']
    SettingsColorPicker: typeof import('./src/components/Settings/SettingsColorPicker.vue')['default']
    SettingsRadioGroup: typeof import('./src/components/Settings/SettingsRadioGroup.vue')['default']
    SettingsRange: typeof import('./src/components/Settings/SettingsRange.vue')['default']
    SettingsSection: typeof import('./src/components/Settings/SettingsSection.vue')['default']
    SettingsSelect: typeof import('./src/components/Settings/SettingsSelect.vue')['default']
    SettingsTextInput: typeof import('./src/components/Settings/SettingsTextInput.vue')['default']
    SettingsToggle: typeof import('./src/components/Settings/SettingsToggle.vue')['default']
    SusLabel: typeof import('./src/components/CircleFifths/sections/SusLabel.vue')['default']
    Suspended: typeof import('./src/components/CircleFifths/sections/Suspended.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    WhiteNote: typeof import('./src/components/PianoKeyboard/classic/WhiteNote.vue')['default']
  }
}
