export const MIDI_CMD: Record<number, string> = {
  0x80: "Note Off",
  0x90: "Note On",
  0xa0: "Poly Aftertouch",
  0xb0: "CC",
  0xc0: "Program Change",
  0xd0: "Chan Aftertouch",
  0xe0: "Pitchwheel",
  0xf0: "SysEx",
  0xf1: "MIDI Time Code  Qtr. Frame",
  0xf2: "Song Position Pointer",
  0xf3: "Song Select",
  0xf4: "Undefined",
  0xf5: "Undefined",
  0xf6: "Tune request",
  0xf7: "EOX",
  0xf8: "Timing clock",
  0xf9: "Undefined",
  0xfa: "Start",
  0xfb: "Continue",
  0xfc: "Stop",
  0xfd: "Undefined",
  0xfe: "Active Sensing",
  0xff: "System Reset",
};

export const MIDI_CC: Record<number, string> = {
  0x0: "Bank Select",
  0x1: "ModWheel",
  0x2: "Breath Ctrl",
  0x4: "Foot Ctrl",
  0x5: "Portamento Time",
  0x6: "Data Entry MSB",
  0x7: "Channel Volume",
  0x8: "Balance",
  0x0a: "Pan",
  0x0b: "Expression Ctrl",
  0x0c: "Effect Control 1",
  0x0d: "Effect Control 2",
  0x10: "General Purpose Ctrl 1",
  0x11: "General Purpose Ctrl 2",
  0x12: "General Purpose Ctrl 3",
  0x13: "General Purpose Ctrl 4",
  0x20: "LSB for Control 0",
  0x40: "Damper Pedal on/off",
  0x41: "Portamento On/Off",
  0x42: "Sostenuto On/Off",
  0x43: "Soft Pedal On/Off",
  0x44: "Legato Footswitch",
  0x45: "Hold 2",
  0x5b: "Effects 1 Depth",
  0x5c: "Effects 2 Depth",
  0x5d: "Effects 3 Depth",
  0x5e: "Effects 4 Depth",
  0x5f: "Effects 5 Depth",
  0x60: "Data Increment",
  0x61: "Data Decrement",
  0x78: "[Channel Mode] All Sound Off",
  0x79: "[Channel Mode] Reset All Ctrls",
  0x7a: "[Channel Mode] Local Control On/Off",
  0x7b: "[Channel Mode] All Notes Off",
  0x7c: "[Channel Mode] Omni Mode Off",
  0x7d: "[Channel Mode] Omni Mode On",
  0x7e: "[Channel Mode] Mono Mode On",
  0x7f: "[Channel Mode] Poly Mode On",
};
